version: '3.1'

services:

  csv-service:
      image: golang:1.11
      working_dir: /app
      volumes:
          - .:/app
          - cache:/go
      command: go run cmd/csv-service/main.go
      depends_on:
        - user-service

  user-service:
      image: golang:1.11
      working_dir: /app
      volumes:
          - .:/app
          - cache:/go
      command: go run cmd/user-service/main.go
      depends_on:
        - mongodb



  mongodb:
    image: mongo
    volumes:
    - mongodb_data:/data/db
    environment:
      STORAGE_ENGINE: wiredTiger


volumes:
  mongodb_data:
  cache:
